// The Emergency Broadcast System. Professionally unhelpful since 1957.
// Only characters the generated font has: A-Z 0-9 ! : . + - / ? , ' ( ) % * & #

export const INTRO = [
  'THE GOVERNMENT SAYS STAY CALM. THE GOVERNMENT HAS LEFT THE BUILDING.',
  'GOOD AFTERNOON, PINE BLUFF. YOUR TOWN HAS BEEN SELECTED FOR INVASION. CONGRATULATIONS.',
  'THIS IS NOT A DRILL. A DRILL WOULD BE BETTER ORGANIZED.',
];

export const AMBIENT = [
  'REMINDER: ALIEN INVASIONS ARE NOT COVERED BY YOUR HOME INSURANCE.',
  'THE HOA REMINDS RESIDENTS THAT CRATERS MUST BE FILLED BY MONDAY.',
  'WEATHER: SUNNY, WITH A 90% CHANCE OF SCREAMING.',
  'TRAFFIC UPDATE: EVERYTHING IS ON FIRE. AVOID EVERYTHING.',
  'SCIENTISTS CONFIRM THEY DID NOT COME IN PEACE. THEY CAME IN SAUCERS.',
  'HR REMINDS YOU THAT BEING VAPORIZED DOES NOT COUNT AS SICK LEAVE.',
  'THE MAYOR HAS ISSUED A STATEMENT: AAAAAAAAAAHH.',
  'IF AN ALIEN ASKS TO SEE YOUR LEADER, POINT AT SOMEONE YOU DISLIKE.',
  'PLEASE STOP CALLING 911. 911 HAS BEEN ABDUCTED.',
  'LOCAL CHURCH REPORTS RECORD ATTENDANCE.',
  'THE PROBING IS RANDOMIZED. THAT IS NOT REASSURING, AND IT IS NOT MEANT TO BE.',
  'REAL ESTATE UPDATE: PROPERTY VALUES ARE NOW A RUMOR.',
  'THE DMV REMAINS OPEN. THE ALIENS ARE TOO SCARED TO GO IN.',
  'PUBLIC SERVICE NOTICE: THE PURPLE ONES BITE. THE BIG PURPLE ONES BITE HARDER.',
  'YOUR COMPLAINT HAS BEEN FORWARDED TO THE MOTHERSHIP. ESTIMATED RESPONSE: VIOLENT.',
  'GARY FROM NUMBER 12 SAYS HE IS FINE. GARY IS NOT FINE.',
  'THE ICE CREAM TRUCK IS STILL PLAYING ITS SONG. NOBODY KNOWS WHO IS DRIVING.',
  'SURVIVAL TIP: RUN AWAY FROM THINGS. SHOOT THE THINGS YOU CANNOT RUN AWAY FROM.',
  'BREAKING: THE CONSPIRACY GUY WAS RIGHT. HE WILL NEVER SHUT UP ABOUT IT NOW.',
  'THIS BROADCAST IS SPONSORED BY SHOTGUNS. SHOTGUNS: BECAUSE DIPLOMACY FAILED.',
];

export const THREAT = [
  { name: 'MILDLY CONCERNING', line: 'THREAT LEVEL: MILDLY CONCERNING. LIKE A WEIRD MOLE.' },
  { name: 'NOTICEABLY ON FIRE', line: 'THREAT LEVEL: NOTICEABLY ON FIRE. PLEASE PANIC IN AN ORDERLY FASHION.' },
  { name: 'DEEPLY UNCOOL', line: 'THREAT LEVEL: DEEPLY UNCOOL. THE BIG ONES ARE OUT NOW.' },
  { name: 'BIBLICAL', line: 'THREAT LEVEL: BIBLICAL. SOMEONE CHECK IF THE FROGS ARE RAINING TOO.' },
  { name: 'CANCEL EVERYTHING', line: 'THREAT LEVEL: CANCEL EVERYTHING. YES, EVEN BRUNCH.' },
  { name: 'WELL, THAT IS IT THEN', line: 'THREAT LEVEL: WELL, THAT IS IT THEN. IT WAS NICE KNOWING ALL OF YOU. MOSTLY.' },
  { name: 'BEYOND HELP', line: 'THREAT LEVEL: BEYOND HELP. WE ARE NOW JUST WATCHING. WITH POPCORN.' },
];

export const NIGHT = [
  'NIGHT FALLS. SO DOES YOUR LIFE EXPECTANCY.',
  'IT IS GETTING DARK. THE ALIENS LOVE THAT. THEY ARE NOCTURNAL AND RUDE.',
  'SUNSET. ROMANTIC, IF YOU IGNORE THE SCREAMING.',
];
export const DAWN = [
  'YOU SURVIVED THE NIGHT. DO NOT GET COCKY.',
  'GOOD MORNING! THE NIGHTMARE CONTINUES, NOW IN DAYLIGHT.',
  'DAWN. COFFEE IS CANCELLED. EVERYTHING IS CANCELLED.',
];
export const METEOR = [
  'SKYFALL! THE SKY IS LITERALLY FALLING. CHICKEN LITTLE SENDS HIS REGARDS.',
  'METEOR SHOWER INCOMING. THIS IS NOT THE ROMANTIC KIND.',
  'ROCKS. FROM SPACE. ON FIRE. LOOK UP. ACTUALLY, DO NOT. RUN.',
];
export const NEST = [
  'A UFO JUST PARKED ON THE LAWN. THE HOA IS FURIOUS.',
  'NEW SAUCER ON THE GROUND. IT IS PRODUCING ALIENS. DESTROY IT, PLEASE AND THANK YOU.',
  'ALIEN DAYCARE HAS OPENED NEARBY. SHOOT IT UNTIL IT CLOSES.',
];
export const MOTHER_IN = [
  'THE MOTHERSHIP HAS ARRIVED. SHE WOULD LIKE TO SPEAK TO YOUR MANAGER.',
  'BIG MAMA IS HERE. SHE IS NOT PROUD OF ANY OF YOU.',
];
export const MOTHER_DOWN = [
  'MOTHERSHIP DOWN! THAT IS GOING TO LEAVE A MARK. AND A CRATER.',
  'YOU KILLED THE MOTHERSHIP. SOMEWHERE, A VERY LARGE ALIEN IS CRYING.',
];
export const MOTHER_LEAVE = ['THE MOTHERSHIP GOT BORED AND LEFT. YOU ARE THAT UNIMPRESSIVE.'];
export const COW = [
  'A COW HAS BEEN ABDUCTED. MILK PRICES SOAR.',
  'ANOTHER COW TAKEN. SHE HAD A FAMILY. WELL, A HERD.',
  'COW ABDUCTED. NOBODY KNOWS WHY THEY WANT THE COWS. NOBODY WANTS TO KNOW.',
];
export const CIV_TAKEN = [
  'GARY GOT ABDUCTED. HIS WIFE SAYS SHE IS DEVASTATED. SHE IS SMILING.',
  'A RESIDENT HAS BEEN PROBED. HE DESCRIBES IT AS THOROUGH.',
  'ONE LESS NEIGHBOR. YOUR LAWN NOW HAS THE BEST CURB APPEAL ON THE STREET.',
  'CIVILIAN TAKEN. THOUGHTS AND PRAYERS. MOSTLY THOUGHTS.',
];
export const CIV_SPAWN = ['SURVIVORS SPOTTED. TRY NOT TO LET THEM DIE. OR DO. WE ARE NOT YOUR MOM.'];
export const TINFOIL = ['I TOLD YOU SO!', 'TOLD YA! TOLD ALL OF YA!', 'WHO IS CRAZY NOW, LINDA?', 'THE FOIL WORKS!'];

export const PICKUP = {
  ammo: ['+12 SHELLS. FEED THE BOOMSTICK.', '+12 SHELLS. DIPLOMACY RESTOCKED.', '+12 SHELLS'],
  medkit: ['+35 HP. BAND-AIDS AND DENIAL.', '+35 HP. WALK IT OFF.', '+35 HP'],
  grenades: ['+2 GRENADES. PULL PIN. THROW. DO NOT REVERSE.', '+2 GRENADES. PROBLEM SOLVERS.'],
  smg: ['SMG! SPRAY AND PRAY. MOSTLY SPRAY.', 'SMG! PRECISION IS FOR COWARDS.'],
  core: ['ALIEN TECH! WHAT COULD POSSIBLY GO WRONG?', 'PLASMA! THEIR GUN, YOUR PROBLEM NOW.'],
};

export const LOW_HP = [
  'YOU LOOK TERRIBLE. MORE TERRIBLE THAN USUAL.',
  'HEALTH CRITICAL. HAVE YOU TRIED NOT GETTING HIT?',
  'YOU ARE LEAKING. THAT IS USUALLY BAD.',
];
export const NO_AMMO = ['OUT OF SHELLS. SWITCHING TO GRANDPA REVOLVER.', 'NO SHELLS LEFT. TRY HARSH LANGUAGE.'];

export const KILLS = {
  10: '10 KILLS. EARTH SAYS THANKS. EARTH WILL NOT BE PAYING YOU.',
  25: '25 KILLS. THE ALIENS HAVE STARTED A GROUP CHAT ABOUT YOU.',
  50: '50 KILLS. STILL NO MEDAL. THE MEDAL GUY GOT PROBED.',
  100: '100 KILLS. THERAPY IS STRONGLY RECOMMENDED. AFTERWARDS.',
  200: '200 KILLS. YOU ARE NOW A SPECIES-LEVEL PROBLEM.',
  400: '400 KILLS. THE ALIENS ARE ASKING FOR A MANAGER. YOU ARE THE MANAGER.',
};

export const DEATH = [
  'THE ALIENS GIVE YOUR PERFORMANCE TWO STARS.',
  'HUMANITY WAS A NICE TRY.',
  'YOUR SACRIFICE WILL BE FORGOTTEN BY THURSDAY.',
  'YOU DIED AS YOU LIVED: SURROUNDED BY STRANGERS.',
  'ON THE BRIGHT SIDE, YOU NO LONGER HAVE TO PAY RENT.',
  'THE PROBE WAS INEVITABLE. YOU JUST MADE IT AWKWARD.',
];

export function rank(t) {
  if (t < 60) return 'TOURIST';
  if (t < 150) return 'MOSTLY HARMLESS';
  if (t < 300) return 'MILDLY USEFUL';
  if (t < 480) return 'LOCAL LEGEND';
  if (t < 720) return 'ALIEN PEST CONTROL';
  if (t < 1080) return 'INTERSTELLAR NUISANCE';
  return 'GOD-TIER REDNECK';
}

export const pickLine = (arr) => arr[Math.floor(Math.random() * arr.length)];
