// The Emergency Broadcast System. Professionally unhelpful since 1957.
// Only characters the generated font has: A-Z 0-9 ! : . + - / ? , ' ( ) % * & #

export const INTRO = [
  'THE GOVERNMENT SAYS STAY CALM. THE GOVERNMENT HAS LEFT THE BUILDING.',
  'GOOD AFTERNOON, PINE BLUFF. YOUR TOWN HAS BEEN SELECTED FOR INVASION. CONGRATULATIONS.',
  'THIS IS NOT A DRILL. A DRILL WOULD BE BETTER ORGANIZED. GET IN A CAR.',
];

export const AMBIENT = [
  'REMINDER: ALIEN INVASIONS ARE NOT COVERED BY YOUR CAR INSURANCE. NEITHER IS ANYTHING YOU ARE DOING.',
  'THE HOA REMINDS RESIDENTS THAT CRATERS MUST BE FILLED BY MONDAY.',
  'WEATHER: SUNNY, WITH A 90% CHANCE OF SCREAMING.',
  'TRAFFIC UPDATE: EVERYTHING IS ON FIRE. AVOID EVERYTHING.',
  'SCIENTISTS CONFIRM THEY DID NOT COME IN PEACE. THEY CAME IN SAUCERS.',
  'HR REMINDS YOU THAT BEING VAPORIZED DOES NOT COUNT AS SICK LEAVE.',
  'THE MAYOR HAS ISSUED A STATEMENT: AAAAAAAAAAHH.',
  'IF AN ALIEN ASKS TO SEE YOUR LEADER, POINT AT SOMEONE YOU DISLIKE.',
  'PLEASE STOP CALLING 911. 911 HAS BEEN ABDUCTED.',
  'LOCAL CHURCH REPORTS RECORD ATTENDANCE.',
  'THE PROBING IS RANDOMIZED. THAT IS NOT REASSURING, AND IT IS NOT MEANT TO BE.',
  'REAL ESTATE UPDATE: PROPERTY VALUES ARE NOW A RUMOR.',
  'THE DMV REMAINS OPEN. THE ALIENS ARE TOO SCARED TO GO IN.',
  'PUBLIC SERVICE NOTICE: THE PURPLE ONES BITE. THE BIG PURPLE ONES EAT CARS.',
  'GARY FROM NUMBER 12 SAYS HE IS FINE. GARY IS NOT FINE.',
  'THE ICE CREAM TRUCK IS STILL PLAYING ITS SONG. NOBODY KNOWS WHO IS DRIVING.',
  'SURVIVAL TIP: ALIENS HATE CAR HORNS. SO DOES EVERYONE ELSE. HONK ANYWAY.',
  'BREAKING: THE CONSPIRACY GUY WAS RIGHT. HE WILL NEVER SHUT UP ABOUT IT NOW.',
  'THIS BROADCAST IS SPONSORED BY CAR INSURANCE. THEY ARE VERY, VERY NERVOUS.',
  'SPEED LIMITS HAVE BEEN SUSPENDED. SO HAS BASIC DECENCY.',
  'PEDESTRIANS ARE REMINDED THAT WALKING IS FOR PEOPLE WHO WANT TO BE PROBED.',
  'DALE\'S EX-WIFE HAS CALLED. SHE SAYS THIS IS TYPICAL.',
];

export const THREAT = [
  { name: 'MILDLY CONCERNING', line: 'THREAT LEVEL: MILDLY CONCERNING. LIKE A WEIRD MOLE.' },
  { name: 'NOTICEABLY ON FIRE', line: 'THREAT LEVEL: NOTICEABLY ON FIRE. PLEASE PANIC IN AN ORDERLY FASHION.' },
  { name: 'DEEPLY UNCOOL', line: 'THREAT LEVEL: DEEPLY UNCOOL. THE BIG ONES ARE OUT NOW. THEY EAT HUBCAPS.' },
  { name: 'BIBLICAL', line: 'THREAT LEVEL: BIBLICAL. SOMEONE CHECK IF THE FROGS ARE RAINING TOO.' },
  { name: 'CANCEL EVERYTHING', line: 'THREAT LEVEL: CANCEL EVERYTHING. YES, EVEN BRUNCH.' },
  { name: 'WELL, THAT IS IT THEN', line: 'THREAT LEVEL: WELL, THAT IS IT THEN. IT WAS NICE KNOWING ALL OF YOU. MOSTLY.' },
  { name: 'BEYOND HELP', line: 'THREAT LEVEL: BEYOND HELP. WE ARE NOW JUST WATCHING. WITH POPCORN.' },
];

export const NIGHT = [
  'NIGHT FALLS. SO DOES YOUR LIFE EXPECTANCY.',
  'IT IS GETTING DARK. THE ALIENS LOVE THAT. THEY ARE NOCTURNAL AND RUDE.',
  'SUNSET. ROMANTIC, IF YOU IGNORE THE SCREAMING.',
];
export const DAWN = [
  'YOU SURVIVED THE NIGHT. DO NOT GET COCKY.',
  'GOOD MORNING! THE NIGHTMARE CONTINUES, NOW IN DAYLIGHT.',
  'DAWN. COFFEE IS CANCELLED. EVERYTHING IS CANCELLED.',
];
export const METEOR = [
  'SKYFALL! THE SKY IS LITERALLY FALLING. CHICKEN LITTLE SENDS HIS REGARDS.',
  'METEOR SHOWER INCOMING. THIS IS NOT THE ROMANTIC KIND. KEEP DRIVING.',
  'ROCKS. FROM SPACE. ON FIRE. LOOK UP. ACTUALLY, DO NOT. FLOOR IT.',
];
export const NEST = [
  'A UFO JUST PARKED ON THE LAWN. THE HOA IS FURIOUS. RAM IT.',
  'NEW SAUCER ON THE GROUND. IT IS PRODUCING ALIENS. HIT IT WITH A CAR. HARD.',
  'ALIEN DAYCARE HAS OPENED NEARBY. A FAST CAR IS THE ONLY FORM OF PROTEST THEY UNDERSTAND.',
];
export const MOTHER_IN = [
  'THE MOTHERSHIP HAS ARRIVED. SHE WOULD LIKE TO SPEAK TO YOUR MANAGER. JUST SURVIVE THE MEETING.',
  'BIG MAMA IS HERE. SHE IS NOT PROUD OF ANY OF YOU. KEEP MOVING UNTIL SHE GETS BORED.',
];
export const MOTHER_LEAVE = ['THE MOTHERSHIP GOT BORED AND LEFT. THIS MEETING COULD HAVE BEEN AN EMAIL.'];
export const COW = [
  'A COW HAS BEEN ABDUCTED. MILK PRICES SOAR.',
  'ANOTHER COW TAKEN. SHE HAD A FAMILY. WELL, A HERD.',
  'COW ABDUCTED. NOBODY KNOWS WHY THEY WANT THE COWS. NOBODY WANTS TO KNOW.',
];
export const CIV_TAKEN = [
  'GARY GOT ABDUCTED. HIS WIFE SAYS SHE IS DEVASTATED. SHE IS SMILING.',
  'A RESIDENT HAS BEEN PROBED. HE DESCRIBES IT AS THOROUGH.',
  'ONE LESS NEIGHBOR. YOUR LAWN NOW HAS THE BEST CURB APPEAL ON THE STREET.',
  'CIVILIAN TAKEN. THOUGHTS AND PRAYERS. MOSTLY THOUGHTS.',
];
export const CIV_SPAWN = ['SURVIVORS SPOTTED. PICK THEM UP. OR DO NOT. WE ARE NOT YOUR MOM.'];
export const TINFOIL = ['I TOLD YOU SO!', 'TOLD YA! TOLD ALL OF YA!', 'WHO IS CRAZY NOW, LINDA?', 'THE FOIL WORKS!'];
export const GIFT = ['TAKE IT, I AM A PACIFIST NOW!', 'HERE! I FOUND THIS IN THE GARAGE!', 'MY HUSBAND WON\'T NEED THIS!', 'IS THIS COVERED BY INSURANCE?'];

export const PICKUP = {
  fuel: ['+FUEL. THE PLANET IS DOOMED ANYWAY.', '+FUEL. UNLEADED. LIKE YOUR JUDGEMENT.'],
  repair: ['DUCT TAPE! CAR +50%. IT IS HOLDING. FOR NOW.', 'REPAIRED. THE CHECK ENGINE LIGHT IS STILL ON. IT ALWAYS WILL BE.'],
  medkit: ['+35 HP. BAND-AIDS AND DENIAL.', '+35 HP. WALK IT OFF.'],
  nitro: ['+2 ALIEN NITRO. WHAT COULD POSSIBLY GO WRONG?', '+2 NITRO. FROM SPACE. PROBABLY NOT STREET LEGAL.'],
};

export const LOW_HP = [
  'YOU LOOK TERRIBLE. MORE TERRIBLE THAN USUAL. GET IN A CAR.',
  'HEALTH CRITICAL. HAVE YOU TRIED NOT GETTING HIT?',
  'YOU ARE LEAKING. THAT IS USUALLY BAD.',
];

export const KILLS = {
  10: '10 ALIENS SPLATTED. EARTH SAYS THANKS. EARTH WILL NOT BE PAYING FOR THE CAR WASH.',
  25: '25 SPLATTED. THE ALIENS HAVE STARTED A GROUP CHAT ABOUT YOUR DRIVING.',
  50: '50 SPLATTED. YOUR BUMPER IS NOW 30% ALIEN.',
  100: '100 SPLATTED. THERAPY IS STRONGLY RECOMMENDED. AFTERWARDS. AND A CAR WASH.',
  200: '200 SPLATTED. YOU ARE NOW A SPECIES-LEVEL TRAFFIC HAZARD.',
  400: '400 SPLATTED. THE ALIENS ARE ASKING FOR A MANAGER. YOU ARE THE MANAGER.',
};

export const DEATH = [
  'THE ALIENS GIVE YOUR PERFORMANCE TWO STARS.',
  'HUMANITY WAS A NICE TRY.',
  'YOUR SACRIFICE WILL BE FORGOTTEN BY THURSDAY.',
  'YOU DIED AS YOU LIVED: ON FOOT, LIKE AN AMATEUR.',
  'ON THE BRIGHT SIDE, YOU NO LONGER HAVE TO PAY FOR THE DAMAGES.',
  'THE PROBE WAS INEVITABLE. YOU JUST MADE IT AWKWARD.',
];

export function rank(t) {
  if (t < 60) return 'LEARNER PERMIT';
  if (t < 150) return 'SUNDAY DRIVER';
  if (t < 300) return 'MILDLY USEFUL';
  if (t < 480) return 'LOCAL LEGEND';
  if (t < 720) return 'ROAD WARRIOR';
  if (t < 1080) return 'INTERSTELLAR NUISANCE';
  return 'GOD-TIER REDNECK';
}

export const pickLine = (arr) => arr[Math.floor(Math.random() * arr.length)];

// --- cars ----------------------------------------------------------------------------------------------
export const CAR_IN = [
  'SPEED LIMITS ARE A SUGGESTION NOW.',
  'YOU HAVE NO LICENSE. NOBODY CARES.',
  'THE OWNER WILL NOT NEED IT ANYMORE. PROBABLY.',
  'MIRROR, SIGNAL, FLOOR IT.',
];
export const CAR_BOOM = ['THE CAR EXPLODED. THE OWNER\'S INSURANCE WILL BE THRILLED.', 'CAR DESTROYED. YOU WALK AGAIN. LIKE A PEASANT.'];
export const CAR_TAKEN = ['YOUR CAR WAS ABDUCTED. YOU WERE NOT. EVEN THE ALIENS HAVE STANDARDS.', 'THE SAUCER TOOK THE CAR AND LEFT YOU. RUDE.'];
export const BAIL = ['YOU BAILED OUT AT FULL SPEED. STUNTMEN HATE THIS ONE TRICK.', 'DIVE! ROLL! REGRET!'];
export const BOARD = ['THANK GOD!', 'NICE CAR. IS IT STOLEN?', 'DRIVE! DRIVE! DRIVE!', 'I CALL SHOTGUN!', 'DO YOU HAVE SNACKS?', 'MIND IF I SCREAM THE WHOLE WAY?'];
export const HONK = ['HONK!', 'HONK HONK!', 'BEEP BEEP, MOTHER***ER!', 'MOVE IT, E.T.!', 'OUT OF THE WAY!', 'HONK IF YOU HATE ALIENS!'];
export const CARJACK = ['HEY! THAT IS MY CAR!', 'I STILL HAVE 3 PAYMENTS LEFT!', 'FINE. TAKE IT. TAKE EVERYTHING.', 'AT LEAST BRING IT BACK WASHED!'];
export const ROAD_RAGE = ['LEARN TO DRIVE!', 'ARE YOU KIDDING ME?!', 'I AM CALLING THE COPS! OH WAIT.', 'MY INSURANCE!'];
export const DODGE = ['WATCH IT!', 'I HAVE INSURANCE!', 'MY FOOT!', 'MANIAC!'];
export const SPLAT = ['SPLAT!', 'SPEED BUMP.', 'HIT AND RUN. MOSTLY RUN.', 'THAT IS GOING TO STAIN.', 'WIPERS ON.'];
export const SPOOKED = ['THE SAUCER WAS STARTLED.', 'IT FLED. HORNS: 1, ALIENS: 0.', 'NOBODY LIKES A HONKER.'];
export const DAMAGE = [
  'PROPERTY DAMAGE: 10,000. YOUR INSURANCE AGENT JUST SAT DOWN.',
  'PROPERTY DAMAGE: 50,000. THE HOA IS DRAFTING A STRONGLY WORDED LETTER.',
  'PROPERTY DAMAGE: 100,000. YOUR INSURANCE AGENT HAS FAINTED.',
  'PROPERTY DAMAGE: 250,000. THEY ARE NAMING A POTHOLE AFTER YOU.',
  'PROPERTY DAMAGE: 1,000,000. CONGRATULATIONS, YOU ARE NOW WORSE THAN THE ALIENS.',
  'PROPERTY DAMAGE: 5,000,000. THE ALIENS ARE TAKING NOTES.',
];

// --- interactions on foot -------------------------------------------------------------------------------
export const FIND = {
  house: [
    'FOUND A FUEL CAN AND A DIVORCE LAWYER\'S BUSINESS CARD.',
    'FOUND A MEDKIT AND SOMEBODY\'S DIARY. YIKES.',
    'DUCT TAPE IN THE SOCK DRAWER. GARY WAS PREPARED.',
    'HALF A LASAGNA. DO NOT CHECK THE DATE.',
    'A TREADMILL USED AS A COAT RACK. AND SOME SUPPLIES.',
    'FAMILY PHOTOS. EVERYONE LOOKS MISERABLE. ALSO: STUFF.',
  ],
  store: ['MEDKIT, SNACKS AND A LOTTERY TICKET. IT LOST.', 'THE REGISTER IS EMPTY. THE ALIENS TOOK THE CASH. WHY?'],
  trailer: ['ALIEN NITRO AND A FRAMED PHOTO OF A UFO. HE KNEW.', 'BEEF JERKY, A JERRY CAN AND A CONSPIRACY WALL.'],
  car: ['FUEL IN THE TRUNK. AND 47 PARKING TICKETS.', 'DUCT TAPE AND A VERY SAD AIR FRESHENER.', 'THE KEYS ARE GONE. THE GAS IS NOT.'],
  bin: ['HALF A BURRITO. NO REGRETS.', 'GARBAGE. SHOCKING, I KNOW.', 'A RACCOON. IT LOOKS DISAPPOINTED IN YOU.'],
  empty: ['NOTHING. SOMEBODY GOT HERE FIRST. PROBABLY A RACCOON.', 'EMPTY. LIKE YOUR PROMISES.'],
};

export const TALK = [
  'FINALLY, A MAN WITH A PLAN!',
  'LEAD THE WAY. I WILL SCREAM SUPPORTIVELY.',
  'IS THE BUS AIR CONDITIONED?',
  'I AM RIGHT BEHIND YOU. WELL, A BIT BEHIND.',
  'MY WIFE WAS PROBED. I AM NOT READY TO TALK ABOUT IT.',
];
export const TINFOIL_TALK = ['I HAVE BEEN WAITING 30 YEARS FOR THIS.', 'TOLD YA. NOW CARRY ME.'];

export const RESCUE = [
  'SURVIVORS EVACUATED. ONE LESS PERSON TO WORRY ABOUT. ONE MORE TO COMPLAIN.',
  'RESCUED! THE BUS IS NOW SLIGHTLY MORE CROWDED AND MUCH MORE ANXIOUS.',
  'DELIVERED. THEY DID NOT TIP. TYPICAL.',
  'TAXI SERVICE COMPLETE. FIVE STARS. THE ALIENS GAVE YOU ONE.',
];

export const PET = ['+10 HP. EMOTIONAL SUPPORT COW.', 'THE COW APPROVES. +10 HP.', 'MOO. (+10 HP)'];
export const PET_DOG = ['GOOD BOY! +6 HP.', 'WHO IS A GOOD BOY? HE IS. +6 HP.', 'THE DOG HAS NO IDEA WHAT IS HAPPENING. +6 HP.'];
export const RIG = ['FUSE LIT. RUN, DALE. RUN. OR DRIVE.', 'THIS IS EITHER GENIUS OR A WARNING LABEL.'];

export const MISSIONS = {
  taxi: { text: 'DELIVER 3 SURVIVORS TO THE EVAC BUS', line: 'DISPATCH: SURVIVORS NEED A RIDE TO THE BUS. YOU ARE A TAXI NOW. CONGRATULATIONS.' },
  roadkill: { text: 'RUN OVER 8 ALIENS', line: 'DISPATCH: THE ALIENS ARE JAYWALKING. TEACH THEM A LESSON. WITH A BUMPER.' },
  demolition: { text: 'CAUSE 20,000 IN PROPERTY DAMAGE', line: 'DISPATCH: THE TOWN IS DOOMED ANYWAY. GO WRECK STUFF. FLAMINGOS ARE FAIR GAME.' },
  search: { text: 'SCAVENGE 3 BUILDINGS', line: 'DISPATCH: WE NEED SUPPLIES. GO THROUGH YOUR NEIGHBORS\' STUFF. THEY WON\'T MIND. THEY\'RE PROBED.' },
  carjack: { text: 'STEAL A CAR FROM A PANICKING DRIVER', line: 'DISPATCH: SOMEBODY IS DRIVING AROUND IN A PERFECTLY GOOD CAR. FIX THAT.' },
  nest: { text: 'RAM THE LANDED SAUCER', line: 'DISPATCH: A SAUCER IS PARKED ON A LAWN. HIT IT WITH A CAR UNTIL IT LEAVES.' },
  pet: { text: 'PET A COW. FOR MORALE.', line: 'DISPATCH: MORALE IS LOW. PET A COW. THAT IS AN ORDER.' },
  gas: { text: 'BLOW UP THE GAS STATION', line: 'DISPATCH: BLOW UP THE GAS STATION. FOR SCIENCE. AND INSURANCE FRAUD.' },
  cow: { text: 'HONK THE SAUCER AWAY FROM THE COW', line: 'DISPATCH: THEY ARE TAKING A COW! DRIVE UNDER THE SAUCER AND HONK. THEY HATE THAT.' },
};
export const MISSION_DONE = ['DISPATCH: NICE WORK. YOUR REWARD IS MORE WORK.', 'DISPATCH: MISSION COMPLETE. WE ARE AS SURPRISED AS YOU.', 'DISPATCH: GOOD JOB. HERE, HAVE SOME STUFF.'];
export const MISSION_FAIL = ['DISPATCH: MISSION FAILED. WE ARE DISAPPOINTED BUT NOT SURPRISED.', 'DISPATCH: WELL. THAT WENT POORLY.'];
